### ISSUE TITLE
Invariant Violation AppRegistry - Metro bundle error: TypeError Cannot call a class as a function

### ISSUE THREAD

**Issue by boovius** [Vlad-Karlin/Pendo-Demo-App-React-Native-React-Navigation#1]
Hi there :) 

Great tutorial. Very helpful beyond the Pendo docs. Followed the instructions here to a "T".

Getting the following error though when running:

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-04 at 12 44 14](https://user-images.githubusercontent.com/3697876/172023399-8ffdc3b8-24d1-4c4c-8936-bd3d7482de58.png)

In the node console: 

```
 ERROR  TypeError: Cannot call a class as a function, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

Using:
 * react-native - 0.63
 * react-navigation/core - 5.15.1
 * pendo-sdk - 2.15.2

Would dearly love some help and insight as to how to get this to work! Thanks so much! 

UPDATE: - I figured this out for my own sake. Turns out, in attempting to get this to work, I had two calls to the `withPendoRN` wrapper in two different places, wrapping up the AppRegistry root exported from my App.tsx with the HOF. So perhaps for those who come across this, check your code to make sure you're didn't mess up by having multiple calls to withPendoRN and don't wrap up the component that is exported from root module.

**Comment by Vlad-Karlin** [comment]
Hey @boovius !

Apologies for the late response and thank you for the useful update.

Closing this issue :)
